name: Configure ssh

on:
  workflow_call:
    inputs:
      secrets:
        SSH_PRIVATE_KEY:
          required: true
        deploy_port:
          required: true
        deploy_host:
          required: true

jobs:
  configure:
    steps:
      - name: Configure ssh
        run: |
          eval $(ssh-agent -s)
          echo "SSH_AUTH_SOCK=$(echo $SSH_AUTH_SOCK)" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$(echo $SSH_AGENT_PID)" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          install -m 700 --directory ~/.ssh
          host_ip=$(host "${{ secrets.deploy_host }}" | awk '{print $NF}')
          ssh-keyscan -p"${{ secrets.deploy_port }}" -H "${{ secrets.deploy_host }}" "$host_ip" >> ~/.ssh/known_hosts
