name: Deploy tagged release

on:
  workflow_call:
    inputs:
      deploy_path:
        required: true
        type: string

      environment:
        required: true
        type: string

    secrets:
      SSH_PRIVATE_KEY:
        required: true
      deploy_port:
        required: true
      deploy_user:
        required: true
      deploy_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure ssh
        run: |
          eval $(ssh-agent -s)
          echo "SSH_AUTH_SOCK=$(echo $SSH_AUTH_SOCK)" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$(echo $SSH_AGENT_PID)" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Scan deploy host key
        run: |
          install -m 700 --directory ~/.ssh
          host_ip=$(host "${{ secrets.deploy_host }}" | awk '{print $NF}')
          ssh-keyscan -p"${{ secrets.deploy_port }}" -H "${{ secrets.deploy_host }}" "$host_ip" >> ~/.ssh/known_hosts

      - name: Deploy site using ssh to ${{ inputs.environment }}
        run: ssh -o ForwardAgent=yes -p"${{ secrets.deploy_port }}" "${{ secrets.deploy_user }}@${{ secrets.deploy_host }}" -- "cd ${{ inputs.deploy_path }} && git fetch --tags && git checkout ${{ github.ref_name }}"

      - name: Use composer install
        if: "${{ inputs.use_composer && inputs.php_version == '' }}"
        run: ssh -o ForwardAgent=yes -p"${{ secrets.deploy_port }}" "${{ secrets.deploy_user }}@${{ secrets.deploy_host }}" -- "cd ${{ inputs.deploy_path }} && command -v composer >/dev/null && composer install --no-dev"

      - name: Use composer install with a specific php version
        if: "${{ inputs.use_composer && inputs.php_version != '' }}"
        run: ssh -o ForwardAgent=yes -p"${{ secrets.deploy_port }}" "${{ secrets.deploy_user }}@${{ secrets.deploy_host }}" -- "cd ${{ inputs.deploy_path }} && command -v php${{ inputs.php_version }} >/dev/null && composer=\$(command -v composer) && php${{ inputs.php_version }} \$composer install --no-dev"
