name: Deploy current branch

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'Environment to run tests against'
      use_composer:
        required: false
        type: boolean
        description: Set to true to use composer install after deploy
      php_version:
        required: false
        type: string
        description: use a specific php version, if not define, it will use the defaut php bin
    secrets:
      DEPLOY_PATH:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      DEPLOY_PORT:
        required: true
      DEPLOY_USER:
        required: true
      DEPLOY_HOST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure ssh
        run: |
          eval $(ssh-agent -s)
          echo "SSH_AUTH_SOCK=$(echo $SSH_AUTH_SOCK)" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$(echo $SSH_AGENT_PID)" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Scan deploy host key
        run: |
          install -m 700 --directory ~/.ssh
          host_ip=$(host "${{ secrets.DEPLOY_HOST }}" | awk '{print $NF}')
          ssh-keyscan -p"${{ secrets.DEPLOY_PORT }}" -H "${{ secrets.DEPLOY_HOST }}" "$host_ip" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Deploy site using ssh to ${{ inputs.environment }}
        run: ssh -o ForwardAgent=yes -p"${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" -- "cd ${{ secrets.DEPLOY_PATH }} && git pull"

      - name: Use composer install
        if: "${{ inputs.use_composer && inputs.php_version == '' }}"
        run: ssh -o ForwardAgent=yes -p"${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" -- "cd ${{ secrets.DEPLOY_PATH }} && command -v composer >/dev/null && composer install --no-dev"

      - name: Use composer install with a specific php version
        if: "${{ inputs.use_composer && inputs.php_version != '' }}"
        run: ssh -o ForwardAgent=yes -p"${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" -- "cd ${{ secrets.DEPLOY_PATH }} && command -v php${{ inputs.php_version }} >/dev/null && composer=\$(command -v composer) && php${{ inputs.php_version }} \$composer install --no-dev"
