name: Deploy current branch

on:
  workflow_call:
    inputs:
      deploy_path:
        required: true
        type: string

    secrets:
      SSH_PRIVATE_KEY:
        required: true
      deploy_port:
        required: true
      deploy_host:
        required: true

jobs:
  runs-on: ubuntu-latest
  deploy:
    steps:
      - name: Deploy site using ssh
        run: |
          port="${{ secrets.deploy_port }}"
          user="${{ secrets.deploy_user }}"
          host="${{ secrets.deploy_host }}"
          path="${{ secrets.deploy_path }}"
          ssh -o ForwardAgent=yes -p"$port" "$user@$host" -- "cd $path && git pull"

